spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

# -------------------------------------------------------------
#  Use MultiTenancyDeploymentConfiguration for auto-deployment
# -------------------------------------------------------------
camunda.bpm.auto-deployment-enabled: false

#  ---------------------------------
#   Setup retry
#   R3 = 3 times
#   PT5S pause 5 seconds between
#  ----------------------------------
camunda.bpm.generic-properties.properties.failed-job-retry-time-cycle: R3/PT5S

# check for a scheduled job every 5 sec. default is 60000/ 1 min
camunda.bpm.job-execution.max-wait: 5000

# cycle
# 0/15 * * ? * * -> Every 15 seconds
# 0 * * ? * * -> At second :00 of every minute

# ----------------------------
#  Rest endpoint security  ---
# ----------------------------
spring.security.user:
  name:     CaptainHook
  password: Rum